version: 1
plugin:
  id: github-integration
  label: "GitHub Integration"
  category: productivity
  summary: "GitHub project operations with quality gates."
  tags:
    - github
    - workflow
    - automation
